service: ami-backup
useDotenv: true
plugins:
  - serverless-dotenv-plugin
  - serverless-ignore

provider:
  name: aws
  runtime: python3.8
  memorySize: 128
  timeout: 900
  region: ${env:REGION}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "ec2:DeregisterImage"
            - "ec2:DescribeInstances"
            - "ec2:DeleteTags"
            - "ec2:CreateTags"
            - "ec2:DescribeSnapshotAttribute"
            - "ec2:DescribeInstanceAttribute"
            - "logs:*"
            - "ec2:CreateImage"
            - "ec2:DescribeSnapshots"
            - "ec2:DescribeInstanceCreditSpecifications"
            - "ec2:DescribeImages"
            - "ec2:DescribeImageAttribute"
            - "ec2:DescribeInstanceStatus"
          Resource:
            - "*"
        - Effect: "Allow"
          Action:
            - "ec2:DeleteSnapshot"
            - "ec2:CreateSnapshots"
            - "ec2:CreateSnapshot"
          Resource:
            - "arn:aws:ec2:*:*:instance/*"
            - "arn:aws:ec2:*::snapshot/*"
            - "arn:aws:ec2:*:*:volume/*"

functions:
  function:
    handler: lambda_function.lambda_handler
    environment:
      CUSTOMER: ${env:CUSTOMER}
      REGION: ${env:REGION}
      RETENTION_DAYS: ${env:RETENTION_DAYS}
      SLACK_ENABLED: ${env:SLACK_ENABLED}
      SLACK_WEBHOOK_URL: ${env:SLACK_WEBHOOK_URL}
    events:
      - schedule: ${env:CRON}
